# Generated by Django 4.0.4 on 2022-06-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(default=float),
            preserve_default=False,
        ),
    ]
